spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:viddb
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

  security:
    user:
      name: vidhan
      password: chandra

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  endpoint:
    health:
      show-details: always

